      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1           RPL,DDSDDT,DRPLDE,DRPLDT,
     2           STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3           NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4           CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)

      IMPLICIT DOUBLE PRECISION (A-H,O-Z), INTEGER (I-N)

      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1     DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2     STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3     PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)

      character(len=150) :: CMNAME   
C
C     ASSERT NDI
C
      IF (NDI.NE.3) THEN
C       WRITE (*, *) ’THIS UMAT MAY ONLY BE USED FOR ELEMENTS
C     1     WITH THREE DIRECT STRESS COMPONENTS’
C       CALL XIT
      ENDIF      
C
C     Elastic properties
C
      EMOD=PROPS(1)
      ENU=PROPS(2) 
C      
      EBULK3=EMOD/(1.D0-2.D0*ENU)
      EG2=EMOD/(1.D0+ENU)
      EG=EG2*0.5D0
      EG3=3.0D0*EG
      ELAM=(EBULK3-EG2)/3.0D0
                
C
C     ELASTIC STIFFNESS
C
      DO K1=1, NDI
       DO K2=1, NDI
        DDSDDE(K2, K1)=ELAM
       END DO
       DDSDDE(K1, K1)=EG2+ELAM
      END DO
      DO K1=NDI+1, NTENS
       DDSDDE(K1 ,K1)=EG
      END DO
C
C     CALCULATE STRESS
C
      DO K1=1, NTENS
       DO K2=1, NTENS
        STRESS(K2)=STRESS(K2)+DDSDDE(K2, K1)*DSTRAN(K1)
       END DO
      END DO
C
      RETURN
      END
